version: "3.7"
services:
  detweet:
    image: ghcr.io/ditsi/detweet:v0.2
    environment:
#      NICKNAME: "NickName"
#      PASSWORD: "password"
      NICKNAME: "DiTsi1"
      PASSWORD: "password"
      TIMEZONE: "Asia/Tashkent"
      START_DATE: "2022-08-07"
      STOP_DATE: "2022-09-07"
      DELETE_TWEETS: "True"
      DELETE_REPLIES: "True"
      DELETE_RETWEETS: "True"

      AUTOSTART: "True"
      BACKUP_PATH: "/tweets.js"
      HEADLESS: "True"
      STATUS_PATH=: "/status"
      MAX_ATTEMPTS: "3"
      WAIT: "15"
    volumes:
      - ./tweets.js:/tweets.js:ro
      - ./status:/status
